import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const readSource = (path) => readFile(new URL(path, import.meta.url), 'utf8')

test('the main shell has one permanent canvas workspace and no right-side chat panel', async () => {
  const page = await readSource('../../src/app/core/main/page.tsx')
  const workspace = await readSource('../../src/app/core/main/canvas/canvas-workspace.tsx')

  assert.doesNotMatch(page, /ImmersiveCanvasLayout/)
  assert.doesNotMatch(page, /isCanvasTabPath/)
  assert.doesNotMatch(page, /<Chat\b/)
  assert.match(page, /<CanvasWorkspace\s*\/>/)
  assert.match(workspace, /<CanvasEditor\s+key=\{activeCanvasId\}/)
  assert.doesNotMatch(workspace, /EditorLayout/)
  assert.match(workspace, /data-canvas-chat-hud/)
})

test('legacy canvas tabs are migration-only and canvas selection does not create editor tabs', async () => {
  const editor = await readSource('../../src/app/core/main/editor/editor-layout.tsx')
  const sidebar = await readSource('../../src/app/core/main/canvas/canvas-sidebar.tsx')
  const startup = await readSource('../../src/app/core/main/canvas/canvas-startup-controller.tsx')
  const articleStore = await readSource('../../src/stores/article.ts')
  const parser = await readSource('../../src/app/core/main/canvas/canvas-tab.ts')
  const searchDialog = await readSource('../../src/components/search-dialog.tsx')
  const tiptapEditor = await readSource('../../src/app/core/main/editor/markdown/tiptap-editor.tsx')

  assert.doesNotMatch(editor, /CanvasEditor/)
  assert.doesNotMatch(editor, /setActiveCanvasId/)
  assert.match(sidebar, /setActiveCanvasId\(project\.id\)/)
  assert.doesNotMatch(startup, /setActiveCanvasId/)
  assert.doesNotMatch(startup, /void \(async \(\) =>/)
  assert.match(startup, /async function initializeCanvasStartup\(projects: CanvasProject\[\]\)/)
  assert.match(startup, /void initAllDatabases\(\)\s*\.then\(\(\) => Promise\.all/)
  assert.match(articleStore, /kind === 'canvas'/)
  assert.match(articleStore, /isCanvasOpenTabPath\(tab\.path\)/)
  assert.match(articleStore, /if \(isLegacyCanvasOpenTab\(tab\)\)/)
  assert.match(articleStore, /setActiveCanvasId\(canvasId\)/)
  assert.doesNotMatch(parser, /createCanvasTab/)
  assert.doesNotMatch(searchDialog, /createCanvasTab/)
  assert.doesNotMatch(tiptapEditor, /createCanvasTab/)
  assert.match(searchDialog, /setActiveCanvasId\(project\.id\)/)
  assert.doesNotMatch(tiptapEditor, /setActiveCanvasId/)
  assert.match(sidebar, /const handleOpen = async \(id: string\) => \{\s*await openProject\(id\)\s*\}/)
  assert.match(sidebar, /const handleCreate = async \(canvasType: CanvasProjectType = 'blank'\) => \{\s*await createProject\(canvasType, t\(`templates\.\$\{canvasType\}`\)\)\s*\}/)
  assert.match(sidebar, /const handleDuplicate = async \(project: CanvasProject\) => \{\s*await duplicateProject\([\s\S]*?\)\s*\}/)
})

test('shell controls retain manual preferences and use current canvas authority after async work', async () => {
  const workspace = await readSource('../../src/app/core/main/canvas/canvas-workspace.tsx')
  const sidebar = await readSource('../../src/app/core/main/canvas/canvas-sidebar.tsx')
  const sidebarStore = await readSource('../../src/stores/sidebar.ts')

  assert.match(workspace, /disabled=\{layout\.autoLeftCollapsed\}/)
  const page = await readSource('../../src/app/core/main/page.tsx')

  assert.doesNotMatch(workspace, /function useWindowWidth/)
  assert.match(workspace, /useWindowSize\(\)/)
  assert.match(workspace, /useEffect\(initSidebarState, \[initSidebarState\]\)/)
  assert.match(workspace, /<ResizeDivider onPointerDown=\{startLeftResize\} \/>/)
  assert.doesNotMatch(workspace, /startDocumentPanelResize/)
  assert.doesNotMatch(workspace, /onResize/)
  assert.match(workspace, /toggleLeftSidebar/)
  assert.doesNotMatch(workspace, /toggleRightSidebar/)
  assert.match(sidebarStore, /startLeftResize: \(event\)/)
  assert.doesNotMatch(sidebarStore, /persistLeftWidth\(set/)
  assert.doesNotMatch(sidebarStore, /persistDocumentPanelWidth\(\s*set/)
  assert.match(sidebarStore, /async function loadSidebarState\(\): Promise<Partial<SidebarState>>/)
  assert.match(sidebarStore, /initSidebarState: \(\) => \{\s*void loadSidebarState\(\)\.then\(state => set\(state\)\)/)
  assert.doesNotMatch(page, /void \(async \(\) =>/)
  assert.match(page, /async function persistCurrentPage\(\)/)
  assert.match(page, /useEffect\(persistCurrentPageOnMount, \[\]\)/)
  assert.match(sidebar, /await deleteProject\(id, syncConfigured\)[\s\S]*useCanvasStore\.getState\(\)\.activeCanvasId === id/)
})
